services:
    caddy:
        image: caddy:2.7.6-alpine
        platform: linux/arm64
        restart: always
        ports:
            - "8080:80"
        volumes:
            - ./Caddyfile:/etc/caddy/Caddyfile
            - caddy_certs:/root/.caddy
            - caddy_config:/config
            - $BLUEPRINT_STATIC_DIR:/var/www/southeastblueprint
            - $SSA_STATIC_DIR:/var/www/southeastssa

    mbtileserver:
        image: ghcr.io/consbio/mbtileserver:0.10.0
        platform: linux/arm64
        restart: always
        volumes:
            - $HOST_TILE_DIR:/tilesets # use $TILE_DIR for staging / production
        ports:
            - "8001:8000"

    redis:
        image: redis:7.2.4-alpine
        platform: linux/arm64
        restart: always

    se-worker:
        image: ghcr.io/astutespruce/secas-docker/blueprint-api:latest
        platform: linux/arm64
        cap_add:
            - SYS_PTRACE
        restart: always
        depends_on:
            - redis
        env_file:
            - .env
        entrypoint: "/home/app/run_xvfb.sh"
        command: ["/usr/local/bin/arq", "api.worker.WorkerSettings"]
        volumes:
            - user_upload:/tmp/se-reports
            - $BLUEPRINT_DATA_DIR:/home/app/data
            - $BLUEPRINT_CODE_DIR/api:/home/app/api # main API
            - $BLUEPRINT_CODE_DIR/analysis:/home/app/analysis # needed for analysis utils
            - $BLUEPRINT_CODE_DIR/constants:/home/app/constants # needed for JSON files for blueprint, indicators
            - $BLUEPRINT_CODE_DIR/examples:/home/app/examples # DEBUG ONLY
            - $BLUEPRINT_CODE_DIR/tests:/home/app/tests # DEBUG ONLY
            - $HOST_TILE_DIR:/data/tiles # DEBUG ONLY

    se-api:
        image: ghcr.io/astutespruce/secas-docker/blueprint-api:latest
        platform: linux/arm64
        restart: always
        depends_on:
            - redis
        env_file:
            - .env
        command:
            [
                "/usr/local/bin/gunicorn",
                "-k",
                "uvicorn.workers.UvicornWorker",
                "--name",
                "uvicorn",
                "-b",
                ":5000",
                "--capture-output",
                "--log-level",
                "DEBUG",
                "api.api:app",
            ]
        volumes:
            - user_upload:/tmp/se-reports
            - $BLUEPRINT_DATA_DIR:/home/app/data
            - $BLUEPRINT_CODE_DIR/api:/home/app/api # main API
            - $BLUEPRINT_CODE_DIR/analysis:/home/app/analysis # needed for analysis utils
            - $BLUEPRINT_CODE_DIR/constants:/home/app/constants # needed for JSON files for blueprint, indicators
        ports:
            - "5000:5000"

    ssa-worker:
        image: ghcr.io/astutespruce/secas-docker/blueprint-api:latest
        restart: always
        depends_on:
            - redis
        env_file:
            - .env
        # entrypoint: "/home/app/run_xvfb.sh"
        command: ["/usr/local/bin/arq", "api.worker.WorkerSettings"]
        volumes:
            - user_upload:/tmp/ssa-reports
            - $BLUEPRINT_DATA_DIR:/home/app/data
            - $SSA_CODE_DIR/api:/home/app/api # main API
            - $SSA_CODE_DIR/analysis:/home/app/analysis # needed for analysis utils
            - $SSA_CODE_DIR/constants:/home/app/constants # needed for datasets JSON file
            - $SSA_CODE_DIR/examples:/home/app/examples # DEBUG ONLY
            - $SSA_CODE_DIR/tests:/home/app/tests # DEBUG ONLY

    ssa-api:
        image: ghcr.io/astutespruce/secas-docker/blueprint-api:latest
        restart: always
        depends_on:
            - redis
        env_file:
            - .env
        command:
            [
                "/usr/local/bin/gunicorn",
                "-k",
                "uvicorn.workers.UvicornWorker",
                "--name",
                "uvicorn",
                "-b",
                ":5000",
                "--capture-output",
                "--log-level",
                "DEBUG",
                "api.api:app",
            ]
        volumes:
            - user_upload:/tmp/ssa-reports
            - $BLUEPRINT_DATA_DIR:/home/app/data
            - $SSA_CODE_DIR/api:/home/app/api # main API
            - $SSA_CODE_DIR/analysis:/home/app/analysis # needed for analysis utils
            - $SSA_CODE_DIR/constants:/home/app/constants # needed for datasets JSON file

volumes:
    caddy_certs:
    caddy_config:
    user_upload:
