version: "3.7"

services:
  caddy:
    image: $CADDY
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_certs:/root/.caddy
      - caddy_config:/config
      - $STATIC_DIR:/var/www

  mbtileserver:
    image: consbio/$MBTILESERVER
    restart: on-failure:5
    volumes:
      - $TILE_DIR:/tilesets

  redis:
    image: $REDIS
    restart: always

  renderer:
    image: ${DOCKER_REGISTRY}/blueprint-renderer:latest
    restart: on-failure:5
    volumes:
      - $TILE_DIR:/app/tiles

  sa-worker:
    image: ${DOCKER_REGISTRY}/blueprint-api:latest
    restart: on-failure:5
    depends_on:
      - redis
      - renderer
    env_file:
      - .env
    command: ["/usr/local/bin/arq", "api.worker.WorkerSettings"]
    volumes:
      - user_upload:/tmp/sa-reports
      - $SA_DATA_DIR:/home/app/data
      - $SA_CODE_DIR/api:/home/app/api # main API
      - $SA_CODE_DIR/analysis:/home/app/analysis # needed for analysis utils
      - $SA_CODE_DIR/constants:/home/app/constants # needed for JSON files for blueprint, indicators
      - $SA_CODE_DIR/examples:/home/app/examples # DEBUG ONLY
      - $SA_CODE_DIR/tests:/home/app/tests # DEBUG ONLY

  sa-api:
    image: ${DOCKER_REGISTRY}/blueprint-api:latest
    restart: on-failure:5
    depends_on:
      - redis
    env_file:
      - .env
    command:
      [
        "/usr/local/bin/gunicorn",
        "-k",
        "uvicorn.workers.UvicornWorker",
        "--name",
        "uvicorn",
        "-b",
        ":5000",
        "--capture-output",
        "--log-level",
        "DEBUG",
        "api.api:app",
      ]
    volumes:
      - user_upload:/tmp/sa-reports
      - $SA_DATA_DIR:/home/app/data
      - $SA_CODE_DIR/api:/home/app/api # main API
      - $SA_CODE_DIR/analysis:/home/app/analysis # needed for analysis utils
      - $SA_CODE_DIR/constants:/home/app/constants # needed for JSON files for blueprint, indicators

  se-worker:
    image: ${DOCKER_REGISTRY}/blueprint-api:latest
    restart: on-failure:5
    depends_on:
      - redis
      - renderer
    env_file:
      - .env
    command: ["/usr/local/bin/arq", "api.worker.WorkerSettings"]
    volumes:
      - user_upload:/tmp/se-reports
      - $SE_DATA_DIR:/home/app/data
      - $SE_CODE_DIR/api:/home/app/api # main API
      - $SE_CODE_DIR/analysis:/home/app/analysis # needed for analysis utils
      - $SE_CODE_DIR/constants:/home/app/constants # needed for JSON files for blueprint, indicators
      - $SE_CODE_DIR/examples:/home/app/examples # DEBUG ONLY
      - $SE_CODE_DIR/tests:/home/app/tests # DEBUG ONLY

  se-api:
    image: ${DOCKER_REGISTRY}/blueprint-api:latest
    restart: on-failure:5
    depends_on:
      - redis
    env_file:
      - .env
    command:
      [
        "/usr/local/bin/gunicorn",
        "-k",
        "uvicorn.workers.UvicornWorker",
        "--name",
        "uvicorn",
        "-b",
        ":5000",
        "--capture-output",
        "--log-level",
        "DEBUG",
        "api.api:app",
      ]
    volumes:
      - user_upload:/tmp/se-reports
      - $SE_DATA_DIR:/home/app/data
      - $SE_CODE_DIR/api:/home/app/api # main API
      - $SE_CODE_DIR/analysis:/home/app/analysis # needed for analysis utils
      - $SE_CODE_DIR/constants:/home/app/constants # needed for JSON files for blueprint, indicators

volumes:
  caddy_certs:
  caddy_config:
  user_upload:
