version: "3.6"
services:
  caddy:
    image: $CADDY
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_certs:/root/.caddy
      - $SA_DIR/ui/public:/var/www

  mbtileserver:
    image: consbio/$MBTILESERVER
    restart: on-failure:5
    volumes:
      - ../../tiles:/tilesets

  redis:
    image: $REDIS
    restart: always

  renderer:
    image: consbio/$MBGLRENDERER
    restart: on-failure:5
    volumes:
      - ../../tiles:/app/tiles

  sa-worker:
    build:
      context: ../..
      dockerfile: docker/api/Dockerfile
    restart: on-failure:5
    depends_on:
      - redis
      - renderer
    env_file:
      - .env
    command: ["/usr/local/bin/arq", "api.worker.WorkerSettings"]
    volumes:
      - user_upload:/tmp/sa-reports
      - $SA_DIR/data:/home/app/data
      - $SA_DIR/api:/home/app/api # main API
      - $SA_DIR/analysis:/home/app/analysis # needed for analysis utils
      - $SA_DIR/constants:/home/app/constants # needed for JSON files for blueprint, indicators
      - $SA_DIR/examples:/home/app/examples # DEBUG ONLY
      - $SA_DIR/tests:/home/app/tests # DEBUG ONLY

  sa-api:
    build:
      context: ../..
      dockerfile: docker/api/Dockerfile
    restart: on-failure:5
    depends_on:
      - redis
    env_file:
      - .env
    command:
      [
        "/usr/local/bin/gunicorn",
        "-k",
        "uvicorn.workers.UvicornWorker",
        "--name",
        "uvicorn",
        "-b",
        ":5000",
        "--capture-output",
        "--log-level",
        "DEBUG",
        "api.api:app",
      ]
    volumes:
      - user_upload:/tmp/sa-reports
      - $SA_DIR/data:/home/app/data
      - $SA_DIR/api:/home/app/api # main API
      - $SA_DIR/analysis:/home/app/analysis # needed for analysis utils
      - $SA_DIR/constants:/home/app/constants # needed for JSON files for blueprint, indicators
    ports:
      - "5000:5000"

volumes:
  caddy_certs:
  user_upload:
