services:
    caddy:
        image: caddy:2.8.4-alpine
        platform: linux/arm64
        restart: always
        ports:
            - "80:80"
        volumes:
            - caddy_config:/config
            - ./Caddyfile:/etc/caddy/Caddyfile
        logging:
            driver: journald
        networks:
            - shared

networks:
    shared:
        driver: bridge
        name: shared

volumes:
    caddy_certs:
    caddy_config:
