version: "3.7"

services:
  sa-ui-build:
    build:
      context: .
      dockerfile: ./Dockerfile.sa
    image: ${DOCKER_REGISTRY}/sa-ui-build:latest
    volumes:
      # isolate node_modules within a volume to prevent modifying on host when
      # building image
      - /app/node_modules
      - $SA_CODE_DIR/ui:/home/app/ui
      - $SA_CODE_DIR/constants:/home/app/constants
    network_mode: "host"

  se-ui-build:
    build:
      context: .
      dockerfile: ./Dockerfile.se
    image: ${DOCKER_REGISTRY}/se-ui-build:latest
    volumes:
      - /app/node_modules
      - $SE_CODE_DIR/ui:/home/app/ui
      - $SE_CODE_DIR/constants:/home/app/constants
    network_mode: "host"
