# Provides: User Interface Builder for South Atlantic

FROM node:16-buster-slim

# install required libGL.so.1 for cwebp
RUN apt update && apt install -y libgl1-mesa-glx libxi6

RUN npm install -g gatsby-cli@4.3 && gatsby telemetry --disable

WORKDIR /app

COPY ./deps/southatlantic/package*.json ./
RUN npm ci

# Note: this needs to run as root because it writes files back to the host