services:
    ui-build-base:
        build:
            context: .
            dockerfile: ./Dockerfile
        image: ghcr.io/astutespruce/secas-docker/ui-build-base:latest
        platform: linux/arm64

    se-ui-build:
        image: ghcr.io/astutespruce/secas-docker/ui-build-base:latest
        platform: linux/arm64
        volumes:
            # NOTE: node_modules are written to the host directory, but are replaced on each build
            - ${BLUEPRINT_CODE_DIR}/ui:/home/app/ui
            - ${BLUEPRINT_CODE_DIR}/constants:/home/app/constants
        network_mode: "host"

    ssa-ui-build:
        image: ghcr.io/astutespruce/secas-docker/ui-build-base:latest
        platform: linux/arm64
        volumes:
            # NOTE: node_modules are written to the host directory, but are replaced on each build
            - ${SSA_CODE_DIR}/ui:/home/app/ui
            - ${SSA_CODE_DIR}/constants:/home/app/constants
        network_mode: "host"
