# Provides: User Interface Builder for South Atlantic
ARG DOCKER_REGISTRY

FROM ${DOCKER_REGISTRY}/ui-build-base:latest

ENV GATSBY_CLI_VERSION 4.3

ARG APP_NAME

COPY ./deps/$APP_NAME/package*.json ./

USER app

RUN npm ci && \
    # install gatsby CLI in local environment
    npm install gatsby-cli@$GATSBY_CLI_VERSION --no-save && \
    gatsby telemetry --disable && \
    rm -rf "/home/app/ui/.cache"
