version: "3.7"

services:
  # blueprint-ui:
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #   image: ${DOCKER_REGISTRY}/blueprint-ui:latest
  #   network_mode: "host"

  sa-ui:
    build:
      context: .
      dockerfile: ./Dockerfile.sa
    image: ${DOCKER_REGISTRY}/sa-ui-build:latest
    volumes:
      # isolate node_modules within a volume to prevent modifying on host
      - node_modules:/app/node_modules
      - $SA_CODE_DIR/ui:/app
      - $SA_CODE_DIR/constants:/constants
    network_mode: "host"

  se-ui:
    build:
      context: .
      dockerfile: ./Dockerfile.sa
    image: ${DOCKER_REGISTRY}/se-ui-build:latest
    volumes:
      - node_modules:/app/node_modules
      - $SE_CODE_DIR/ui:/app
      - $SE_CODE_DIR/constants:/constants
    network_mode: "host"

volumes:
  node_modules:
