version: "3.7"

services:
  sa-ui-build:
    build:
      context: .
      dockerfile: ./Dockerfile.sa
    image: ${DOCKER_REGISTRY}/sa-ui-build:latest
    entrypoint: gatsby
    volumes:
      - $SA_CODE_DIR/ui:/app
      - $SA_CODE_DIR/constants:/constants
      # cache node_modules in volume so these aren't recreated each time container is run
      - /app/node_modules
    network_mode: "host"

  se-ui-build:
    build:
      context: .
      dockerfile: ./Dockerfile.se
    image: ${DOCKER_REGISTRY}/se-ui-build:latest
    entrypoint: gatsby
    volumes:
      - $SE_CODE_DIR/ui:/app
      - $SE_CODE_DIR/constants:/constants
      # cache node_modules in volume so these aren't recreated each time container is run
      - /app/node_modules
    network_mode: "host"
