version: "3.7"

services:
  ui-build-base:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: ${DOCKER_REGISTRY}/ui-build-base:latest
    platform: linux/amd64

  sa-ui-build:
    image: ${DOCKER_REGISTRY}/ui-build-base:latest
    platform: linux/amd64
    volumes:
      # NOTE: node_modules are written to the host directory, but are replaced on each build
      - ${SA_CODE_DIR}/ui:/home/app/ui
      - ${SA_CODE_DIR}/constants:/home/app/constants
    network_mode: "host"

  se-ui-build:
    image: ${DOCKER_REGISTRY}/ui-build-base:latest
    platform: linux/amd64
    volumes:
      # NOTE: node_modules are written to the host directory, but are replaced on each build
      - ${SE_CODE_DIR}/ui:/home/app/ui
      - ${SE_CODE_DIR}/constants:/home/app/constants
    network_mode: "host"

  pixelfilter-demo-build:
    image: ${DOCKER_REGISTRY}/ui-build-base:latest
    platform: linux/amd64
    volumes:
      # NOTE: node_modules are written to the host directory, but are replaced on each build
      - ${PIXELFILTER_CODE_DIR}:/home/app
    network_mode: "host"