version: "3.7"

services:
    caddy:
        image: caddy:2.7.6-alpine
        platform: linux/arm64
        restart: always
        ports:
            - "80:80"
        volumes:
            - ./Caddyfile:/etc/caddy/Caddyfile
            - caddy_certs:/data
            - caddy_config:/config
            - $STATIC_DIR:/var/www
        logging:
            driver: journald
        networks:
            - shared

    mbtileserver:
        image: ghcr.io/consbio/mbtileserver:0.10.0
        platform: linux/arm64
        restart: always
        command: "--tiles-only"
        volumes:
            - $TILE_DIR:/tilesets
        logging:
            driver: journald
        networks:
            - shared

    redis:
        image: redis:7.2.4-alpine
        platform: linux/arm64
        restart: always
        logging:
            driver: journald
        networks:
            - shared

    se-worker:
        image: ghcr.io/astutespruce/secas-docker/blueprint-api:latest
        platform: linux/arm64
        restart: always
        depends_on:
            - redis
        external_links:
            - redis
        env_file:
            - .env
        entrypoint: "/home/app/run_xvfb.sh"
        command: ["/usr/local/bin/arq", "api.worker.WorkerSettings"]
        volumes:
            - user_upload:/tmp/se-reports
            - $SE_DATA_DIR:/home/app/data
            - $SE_CODE_DIR/api:/home/app/api # main API
            - $SE_CODE_DIR/analysis:/home/app/analysis # needed for analysis utils
            - $SE_CODE_DIR/constants:/home/app/constants # needed for JSON files for blueprint, indicators
            - $TILE_DIR:/data/tiles
        logging:
            driver: journald
        networks:
            - shared

    se-api:
        image: ghcr.io/astutespruce/secas-docker/blueprint-api:latest
        platform: linux/arm64
        restart: always
        depends_on:
            - redis
            - se-worker
        external_links:
            - redis
        env_file:
            - .env
        command:
            [
                "/usr/local/bin/gunicorn",
                "-k",
                "uvicorn.workers.UvicornWorker",
                "--name",
                "uvicorn",
                "--workers",
                "1",
                "-b",
                ":5000",
                "api.api:app",
            ]
        volumes:
            - user_upload:/tmp/se-reports
            - $SE_DATA_DIR:/home/app/data
            - $SE_CODE_DIR/api:/home/app/api # main API
            - $SE_CODE_DIR/analysis:/home/app/analysis # needed for analysis utils
            - $SE_CODE_DIR/constants:/home/app/constants # needed for JSON files for blueprint, indicators
        logging:
            driver: journald
        networks:
            - shared

    ssa-worker:
        image: ghcr.io/astutespruce/secas-docker/blueprint-api:latest
        platform: linux/arm64
        restart: always
        depends_on:
            - redis
        external_links:
            - redis
        env_file:
            - .env
        command: ["/usr/local/bin/arq", "api.worker.WorkerSettings"]
        volumes:
            - user_upload:/tmp/ssa-reports
            - $SE_DATA_DIR:/home/app/data
            - $SSA_CODE_DIR/api:/home/app/api # main API
            - $SSA_CODE_DIR/analysis:/home/app/analysis # needed for analysis utils
            - $SSA_CODE_DIR/constants:/home/app/constants # needed for datasets JSON file
        logging:
            driver: journald
        networks:
            - shared

    ssa-api:
        image: $ghcr.io/astutespruce/secas-docker/blueprint-api:latest
        platform: linux/arm64
        restart: always
        depends_on:
            - redis
            - ssa-worker
        external_links:
            - redis
        env_file:
            - .env
        command:
            [
                "/usr/local/bin/gunicorn",
                "-k",
                "uvicorn.workers.UvicornWorker",
                "--name",
                "uvicorn",
                "--workers",
                "1",
                "-b",
                ":5000",
                "api.api:app",
            ]
        volumes:
            - user_upload:/tmp/ssa-reports
            - $SE_DATA_DIR:/home/app/data
            - $SSA_CODE_DIR/api:/home/app/api # main API
            - $SSA_CODE_DIR/analysis:/home/app/analysis # needed for analysis utils
            - $SSA_CODE_DIR/constants:/home/app/constants # needed for datasets JSON file
        logging:
            driver: journald
        networks:
            - shared

networks:
    shared:
        driver: bridge
        name: shared

volumes:
    caddy_certs:
    caddy_config:
    user_upload:
