version: "3.6"
services:
  redis:
    image: ${DOCKER_REGISTRY}/redis:6.0.9-alpine
    # logging:
    #   driver: journald
    networks:
      - shared

  mbtileserver:
    image: ${DOCKER_REGISTRY}/mbtileserver:latest
    restart: on-failure:5
    volumes:
      # - /data/tiles:/tilesets
      # FIXME:
      - ../../tiles:/tilesets
    # logging:
    #   driver: journald
    networks:
      - shared

  renderer:
    image: ${DOCKER_REGISTRY}/mbgl-renderer:latest
    restart: on-failure:5
    healthcheck:
      interval: 5m
      timeout: 10s
      retries: 5
      start_period: 30s
    volumes:
      # - /data/tiles:/app/tiles
      # FIXME:
      - ../../tiles:/app/tiles
    # logging:
    #   driver: journald
    networks:
      - shared

  caddy:
    image: ${DOCKER_REGISTRY}/caddy:2.2.1-alpine
    depends_on:
      - mbtileserver
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_certs:/data
      - caddy_config:/config
      - /var/www:/var/www
    # logging:
    #   driver: journald
    networks:
      - shared

  sa-api:
    image: ${DOCKER_REGISTRY}/blueprint-api:latest
    restart: on-failure:5
    depends_on:
      - redis
    external_links:
      - redis
    env_file:
      - .env
    command: [
        "/usr/local/bin/gunicorn",
        "-k",
        "uvicorn.workers.UvicornWorker",
        "--name",
        "uvicorn",
        "--workers",
        "1", # TODO: make this higher on production
        "-b",
        ":5000",
        "api.api:app",
      ]
    volumes:
      - user_upload:/tmp/sa-reports
      - ../../data:/home/app/data ## local dev
      - ../../api:/home/app/api # main API
      - ../../analysis:/home/app/analysis # needed for analysis utils
      - ../../constants:/home/app/constants # needed for JSON files for blueprint, indicators
    # logging:
    #   driver: journald
    networks:
      - shared

  sa-worker:
    image: ${DOCKER_REGISTRY}/blueprint-api:latest
    restart: on-failure:5
    depends_on:
      - redis
      - renderer
    external_links:
      - redis
      - renderer
    env_file:
      - .env
    command: ["/usr/local/bin/arq", "api.worker.WorkerSettings"]
    volumes:
      - user_upload:/tmp/sa-reports
      - ../../data:/home/app/data ## local dev
      - ../../api:/home/app/api # main API
      - ../../analysis:/home/app/analysis # needed for analysis utils
      - ../../constants:/home/app/constants # needed for JSON files for blueprint, indicators
    # logging:
    #   driver: journald
    networks:
      - shared

networks:
  shared:
    driver: bridge
    name: shared

volumes:
  caddy_certs:
  caddy_config:
  user_upload:
